# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: SSH into server and deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@185.206.215.65 << 'EOF'        

          cd KRPP/KRPP2024front
          ps aux | grep 'serve -s dist' | grep -v grep | awk '{print $2}' | xargs kill -9
          git pull origin main
          npm cache clean --force
          rm -rf node_modules
          rm -y package-lock.json 
          npm install || true 
          npm run build || true

          nohup serve -s dist -p 3000 > frontend.log 2>&1 &
          exit

        EOF
